version: 0

system: # These are system level configs
    self: A200-1
    hosts: # These are the hosts that are involved in this system
        platform: # The main computer for this system, ie the robot's computer
            A200-1: 192.168.131.1
        onboard: # These are additional on-board computers such as a secondary computer or software kit
            A200-B: 192.168.131.5
            ONAV-KIT: 192.168.131.10
        remote: # These are remote machines which need to interact with this system such as laptops or other robots
            CPR12345: 10.10.10.101
            USERS-PC: 10.10.10.1
    ros2:
        namespace: HOSTNAME
        domain_id: 123
        rmw_implementation: rmw_fastrtps_cpp

platform: # These are are parameters specific to a a platform
    serial_number: cpr-a200-0001
    decorations: # Platform specific accessories
        front_bumper:
            extension: 0.1
            model: wibotic
        rear_bumper:
            extension: 0
            model: default
        top_plate:
            model: pacs
    extras:
        urdf: /fake/path/empty.urdf.xacro
        control: /fake/path/empty.yaml

mounts:
    fath_pivot:
      - parent: "top_plate_mount_a1"
        angle: 1.5707
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
      - parent: "top_plate_mount_a2"
        angle: 0.0
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
    riser:
      - rows: 8
        columns: 7
        thickness: 0.00635
        parent: "top_plate_mount_a1"
        xyz: [0.0, 0.0, 0.1]
        rpy: [0.0, 0.0, 0.0]
      - rows: 1
        columns: 7
        thickness: 0.00635
        parent: "top_plate_mount_a6"
        xyz: [0.0, 0.0, 0.2]
        rpy: [0.0, 0.0, 0.0]
    bracket:
      - model: "horizontal"
        parent: "riser_1_mount_g6"
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
      - model: "vertical"
        parent: "riser_1_mount_a6"
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]

# Sensors: grouped by sensor types.
#  - model: unique model of that sensor type
#  - urdf_enabled: toggle to add model to description
#  - launch_enabled: toggle to add node to launch file
sensors:
    # List of Cameras
    camera:
      - model: flir_blackfly
        urdf_enabled: true
        launch_enabled: true
        connection_type: USB3
        encoding: BayerRG8
        fps: 30
        serial: 0
        parent: base_link
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
      - model: intel_realsense
        urdf_enabled: true
        launch_enabled: true
        fps: 30
        serial: 0
        width: 640
        height: 480
        depth_enabled: true
        depth_fps: 30
        depth_width: 640
        depth_height: 480
        parent: base_link
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
    lidar2d:
      - model: sick_lms1xx
        urdf_enabled: true
        launch_enabled: true
        ip: 192.168.131.20
        port: 6000
        min_angle: -3.1415
        max_angle: 3.1415
        parent: base_link
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
      - model: hokuyo_ust10
        urdf_enabled: true
        launch_enabled: true
        ip: 192.168.131.21
        port: 6000
        min_angle: -3.1415
        max_angle: 3.1415
        parent: base_link
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
